CREATE TABLE COMODO (
    ID_COMODO SERIAL PRIMARY KEY,
    NOME_COMODO VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE DISPOSITIVO (
    ID_DISPOSITIVO SERIAL PRIMARY KEY,
    ID_COMODO INT NOT NULL,
    NOME_DISPOSITIVO VARCHAR(100) NOT NULL,
    ESTADO_DISPOSITIVO BOOLEAN NOT NULL DEFAULT FALSE,
    ATIVO BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ID_COMODO) REFERENCES COMODO (ID_COMODO)
);

CREATE TABLE CENA (
    ID_CENA SERIAL PRIMARY KEY,
    NOME_CENA VARCHAR(100) NOT NULL,
    ESTADO_CENA BOOLEAN NOT NULL DEFAULT TRUE 
    ATIVO BOOLEAN DEFAULT TRUE,
);

CREATE TABLE ACAO (
    ID_ACAO SERIAL PRIMARY KEY,
    ID_CENA INT NOT NULL,
    ID_DISPOSITIVO INT NOT NULL,
    TIPO_ACAO VARCHAR(50) NOT NULL, 
    INTERVALO_SEGUNDOS INT DEFAULT 0,
    FOREIGN KEY (ID_CENA) REFERENCES CENA (ID_CENA) ON DELETE CASCADE, 
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES DISPOSITIVO (ID_DISPOSITIVO)
);
